version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: movie_db
      MYSQL_USER: movie_user
      MYSQL_PASSWORD: movie1234
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - movie-network

  redis:
    image: redis:7
    container_name: movie_redis
    ports:
      - "6380:6379"
    networks:
      - movie-network

volumes:
  mysql_data:

networks:
  movie-network:
