spring:
  datasource:
    url: jdbc:mysql://localhost:3307/movie_db
    username: movie_user
    password: movie1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: MyHikariPool

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Redis 연결 설정 예시
  data:
    redis:
      host: localhost
      port: 6380

# 기타 사용자 설정 (예: secret key 등)
secretkey: